allowBuilds:
  '@firebase/util': true
  protobufjs: true
overrides:
  uuid: "11.1.1"
  brace-expansion: "2.1.4"
  undici: "6.28.0"
  websocket-driver: "0.7.5"
  tmp: "0.2.7"
  js-yaml: "4.3.1"
  "@babel/core": "7.29.7"
